# Generated by Django 4.2.4 on 2023-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0011_remove_playlist_library'),
        ('library_app', '0008_library_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='songs',
        ),
        migrations.AddField(
            model_name='library',
            name='platlist',
            field=models.ManyToManyField(null=True, to='playlist_app.playlist'),
        ),
    ]
