# Generated by Django 4.2.4 on 2023-08-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0014_alter_playlist_songs'),
        ('library_app', '0009_remove_library_songs_library_platlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='platlist',
        ),
        migrations.AddField(
            model_name='library',
            name='playlist',
            field=models.ManyToManyField(to='playlist_app.playlist'),
        ),
    ]
