# Generated by Django 4.2.4 on 2023-08-09 02:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song_app', '0001_initial'),
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=255)),
                ('max_songs', models.PositiveBigIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('libraries', models.ManyToManyField(to='library_app.library')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_app.playlist')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='song_app.song')),
            ],
        ),
    ]
