# Generated by Django 4.2.4 on 2023-08-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist_song',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist_app.playlist_song'),
        ),
    ]
