# Generated by Django 4.2.4 on 2023-08-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0002_remove_playlist_song_playlist_playlist_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist',
            new_name='songs',
        ),
    ]
