# Generated by Django 4.2.4 on 2023-08-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0003_rename_playlist_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='libraries',
        ),
    ]
