# Generated by Django 4.2.4 on 2023-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_remove_library_playlist'),
        ('playlist_app', '0005_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist',
            field=models.ManyToManyField(to='library_app.library'),
        ),
    ]
