# Generated by Django 4.2.4 on 2023-08-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0001_initial'),
        ('playlist_app', '0012_remove_playlist_songs_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(null=True, to='song_app.song'),
        ),
    ]
