# Generated by Django 4.2.4 on 2023-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0013_remove_playlist_songs_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(null=True, to='playlist_app.playlist_song'),
        ),
    ]
