# Generated by Django 4.2.4 on 2023-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0001_initial'),
        ('playlist_app', '0022_delete_playlist_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='song_app.song'),
        ),
    ]
