# Generated by Django 4.2.4 on 2023-08-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_remove_library_playlist'),
        ('song_app', '0001_initial'),
        ('playlist_app', '0023_alter_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='Library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.library'),
        ),
        migrations.CreateModel(
            name='Playlist_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_app.playlist')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='song_app.song')),
            ],
        ),
    ]
