# Generated by Django 4.2.4 on 2023-08-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0025_alter_playlist_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='Library',
            new_name='library',
        ),
    ]
