# Generated by Django 4.2.4 on 2023-08-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_remove_library_playlist'),
        ('playlist_app', '0026_rename_library_playlist_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='library_app.library'),
        ),
    ]
