# Generated by Django 4.2.4 on 2023-08-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0027_alter_playlist_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist_song',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_song', to='playlist_app.playlist'),
        ),
    ]
