# Generated by Django 4.2.4 on 2023-08-24 00:50

from django.db import migrations, models
import playlist_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0031_alter_playlist_song_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(max_length=255, validators=[playlist_app.validators.validate_playlist_name]),
        ),
    ]
