# Generated by Django 4.2.4 on 2023-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
