# Generated by Django 4.2.4 on 2023-08-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(related_name='song', to='song_app.genre'),
        ),
    ]
