# Generated by Django 4.2.4 on 2023-08-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0006_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='song', to='song_app.genre'),
        ),
    ]
