# Generated by Django 4.2.4 on 2023-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0007_alter_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_song_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
