# Generated by Django 4.2.4 on 2023-08-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0008_song_spotify_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
